services:
  api:
    container_name: api
    build: 
      context: .
      dockerfile: ./apps/api/Dockerfile
  
    ports:
      - "8081:8081"
    networks:
      - app_network
    env_file:
      - ./apps/api/.env
  redis:
    image: "redis:alpine"

  postgres:
    image: "postgres:15"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"


networks:
  app_network:
    external: true