name: CI
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ master ]
    paths: 
      -api/**
jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - name: Deploy Api
        uses: action/checkout@2
      
      - name: Deploy Api
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script_stop: true
          command_timeout: 5m
          script: |
            cd /home/reserva99
            git pull
            docker compose build --no-cache api
            docker compose up -d api
          
